/*
 * This source file was generated by the Gradle 'init' task
 */
package org.rentalpos;

public class RentalPosApp {
    public String getGreeting() {
        return "Bill's Rental Point of Sale system";
    }

    public static void main(String[] args) {
        System.out.println(new RentalPosApp().getGreeting());
    }
}
