/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;

import java.util.Map;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    
    @Test
    public void inventoryServiceReturnsToolUsingToolCode(){
        String toolCode = "CHNS";
        Map<String,Tool> map = Map.of(toolCode, new Tool(toolCode,"Chainsaw", "Stihl"));
    	iInventoryService inventoryService = new InventoryService(map);
    	

    	Tool tool = inventoryService.findTool(toolCode);
    	
    	assertNotNull(tool);
    	
    	
    }
}
